version: '3.1'
services:
  pisignage:
      build: .
      depends_on:
      ports:
        - 3000:3000
      restart: always
      environment:
        MONGO_URI: mongodb://mongo/pisignage-server
        NODE_ENV: docker

